// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "shiporder.h"

// Shiporder
// 

const Shiporder::Orderperson_type& Shiporder::
Orderperson () const
{
  return this->Orderperson_.get ();
}

Shiporder::Orderperson_type& Shiporder::
Orderperson ()
{
  return this->Orderperson_.get ();
}

void Shiporder::
Orderperson (const Orderperson_type& x)
{
  this->Orderperson_.set (x);
}

void Shiporder::
Orderperson (::std::unique_ptr< Orderperson_type > x)
{
  this->Orderperson_.set (std::move (x));
}

const Shiporder::Shipto_type& Shiporder::
Shipto () const
{
  return this->Shipto_.get ();
}

Shiporder::Shipto_type& Shiporder::
Shipto ()
{
  return this->Shipto_.get ();
}

void Shiporder::
Shipto (const Shipto_type& x)
{
  this->Shipto_.set (x);
}

void Shiporder::
Shipto (::std::unique_ptr< Shipto_type > x)
{
  this->Shipto_.set (std::move (x));
}

const Shiporder::Item_sequence& Shiporder::
Item () const
{
  return this->Item_;
}

Shiporder::Item_sequence& Shiporder::
Item ()
{
  return this->Item_;
}

void Shiporder::
Item (const Item_sequence& s)
{
  this->Item_ = s;
}

const Shiporder::Orderid_type& Shiporder::
Orderid () const
{
  return this->Orderid_.get ();
}

Shiporder::Orderid_type& Shiporder::
Orderid ()
{
  return this->Orderid_.get ();
}

void Shiporder::
Orderid (const Orderid_type& x)
{
  this->Orderid_.set (x);
}

void Shiporder::
Orderid (::std::unique_ptr< Orderid_type > x)
{
  this->Orderid_.set (std::move (x));
}


// Shipto
// 

const Shipto::name_type& Shipto::
name () const
{
  return this->name_.get ();
}

Shipto::name_type& Shipto::
name ()
{
  return this->name_.get ();
}

void Shipto::
name (const name_type& x)
{
  this->name_.set (x);
}

void Shipto::
name (::std::unique_ptr< name_type > x)
{
  this->name_.set (std::move (x));
}

const Shipto::address_type& Shipto::
address () const
{
  return this->address_.get ();
}

Shipto::address_type& Shipto::
address ()
{
  return this->address_.get ();
}

void Shipto::
address (const address_type& x)
{
  this->address_.set (x);
}

void Shipto::
address (::std::unique_ptr< address_type > x)
{
  this->address_.set (std::move (x));
}

const Shipto::city_type& Shipto::
city () const
{
  return this->city_.get ();
}

Shipto::city_type& Shipto::
city ()
{
  return this->city_.get ();
}

void Shipto::
city (const city_type& x)
{
  this->city_.set (x);
}

void Shipto::
city (::std::unique_ptr< city_type > x)
{
  this->city_.set (std::move (x));
}

const Shipto::country_type& Shipto::
country () const
{
  return this->country_.get ();
}

Shipto::country_type& Shipto::
country ()
{
  return this->country_.get ();
}

void Shipto::
country (const country_type& x)
{
  this->country_.set (x);
}

void Shipto::
country (::std::unique_ptr< country_type > x)
{
  this->country_.set (std::move (x));
}


// Item
// 

const Item::title_type& Item::
title () const
{
  return this->title_.get ();
}

Item::title_type& Item::
title ()
{
  return this->title_.get ();
}

void Item::
title (const title_type& x)
{
  this->title_.set (x);
}

void Item::
title (::std::unique_ptr< title_type > x)
{
  this->title_.set (std::move (x));
}

const Item::note_optional& Item::
note () const
{
  return this->note_;
}

Item::note_optional& Item::
note ()
{
  return this->note_;
}

void Item::
note (const note_type& x)
{
  this->note_.set (x);
}

void Item::
note (const note_optional& x)
{
  this->note_ = x;
}

void Item::
note (::std::unique_ptr< note_type > x)
{
  this->note_.set (std::move (x));
}

const Item::quantity_type& Item::
quantity () const
{
  return this->quantity_.get ();
}

Item::quantity_type& Item::
quantity ()
{
  return this->quantity_.get ();
}

void Item::
quantity (const quantity_type& x)
{
  this->quantity_.set (x);
}

const Item::price_type& Item::
price () const
{
  return this->price_.get ();
}

Item::price_type& Item::
price ()
{
  return this->price_.get ();
}

void Item::
price (const price_type& x)
{
  this->price_.set (x);
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// Shiporder
//

Shiporder::
Shiporder (const Orderperson_type& Orderperson,
           const Shipto_type& Shipto,
           const Orderid_type& Orderid)
: ::xml_schema::type (),
  Orderperson_ (Orderperson, this),
  Shipto_ (Shipto, this),
  Item_ (this),
  Orderid_ (Orderid, this)
{
}

Shiporder::
Shiporder (const Orderperson_type& Orderperson,
           ::std::unique_ptr< Shipto_type > Shipto,
           const Orderid_type& Orderid)
: ::xml_schema::type (),
  Orderperson_ (Orderperson, this),
  Shipto_ (std::move (Shipto), this),
  Item_ (this),
  Orderid_ (Orderid, this)
{
}

Shiporder::
Shiporder (const Shiporder& x,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  Orderperson_ (x.Orderperson_, f, this),
  Shipto_ (x.Shipto_, f, this),
  Item_ (x.Item_, f, this),
  Orderid_ (x.Orderid_, f, this)
{
}

Shiporder::
Shiporder (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  Orderperson_ (this),
  Shipto_ (this),
  Item_ (this),
  Orderid_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
    this->parse (p, f);
  }
}

void Shiporder::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // Orderperson
    //
    if (n.name () == "Orderperson" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< Orderperson_type > r (
        Orderperson_traits::create (i, f, this));

      if (!Orderperson_.present ())
      {
        this->Orderperson_.set (::std::move (r));
        continue;
      }
    }

    // Shipto
    //
    if (n.name () == "Shipto" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< Shipto_type > r (
        Shipto_traits::create (i, f, this));

      if (!Shipto_.present ())
      {
        this->Shipto_.set (::std::move (r));
        continue;
      }
    }

    // Item
    //
    if (n.name () == "Item" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< Item_type > r (
        Item_traits::create (i, f, this));

      this->Item_.push_back (::std::move (r));
      continue;
    }

    break;
  }

  if (!Orderperson_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Orderperson",
      "");
  }

  if (!Shipto_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Shipto",
      "");
  }

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "Orderid" && n.namespace_ ().empty ())
    {
      this->Orderid_.set (Orderid_traits::create (i, f, this));
      continue;
    }
  }

  if (!Orderid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "Orderid",
      "");
  }
}

Shiporder* Shiporder::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class Shiporder (*this, f, c);
}

Shiporder& Shiporder::
operator= (const Shiporder& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->Orderperson_ = x.Orderperson_;
    this->Shipto_ = x.Shipto_;
    this->Item_ = x.Item_;
    this->Orderid_ = x.Orderid_;
  }

  return *this;
}

Shiporder::
~Shiporder ()
{
}

// Shipto
//

Shipto::
Shipto (const name_type& name,
        const address_type& address,
        const city_type& city,
        const country_type& country)
: ::xml_schema::type (),
  name_ (name, this),
  address_ (address, this),
  city_ (city, this),
  country_ (country, this)
{
}

Shipto::
Shipto (const Shipto& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  name_ (x.name_, f, this),
  address_ (x.address_, f, this),
  city_ (x.city_, f, this),
  country_ (x.country_, f, this)
{
}

Shipto::
Shipto (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  name_ (this),
  address_ (this),
  city_ (this),
  country_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void Shipto::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // name
    //
    if (n.name () == "name" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< name_type > r (
        name_traits::create (i, f, this));

      if (!name_.present ())
      {
        this->name_.set (::std::move (r));
        continue;
      }
    }

    // address
    //
    if (n.name () == "address" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< address_type > r (
        address_traits::create (i, f, this));

      if (!address_.present ())
      {
        this->address_.set (::std::move (r));
        continue;
      }
    }

    // city
    //
    if (n.name () == "city" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< city_type > r (
        city_traits::create (i, f, this));

      if (!city_.present ())
      {
        this->city_.set (::std::move (r));
        continue;
      }
    }

    // country
    //
    if (n.name () == "country" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< country_type > r (
        country_traits::create (i, f, this));

      if (!country_.present ())
      {
        this->country_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "name",
      "");
  }

  if (!address_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "address",
      "");
  }

  if (!city_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "city",
      "");
  }

  if (!country_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "country",
      "");
  }
}

Shipto* Shipto::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class Shipto (*this, f, c);
}

Shipto& Shipto::
operator= (const Shipto& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->name_ = x.name_;
    this->address_ = x.address_;
    this->city_ = x.city_;
    this->country_ = x.country_;
  }

  return *this;
}

Shipto::
~Shipto ()
{
}

// Item
//

Item::
Item (const title_type& title,
      const quantity_type& quantity,
      const price_type& price)
: ::xml_schema::type (),
  title_ (title, this),
  note_ (this),
  quantity_ (quantity, this),
  price_ (price, this)
{
}

Item::
Item (const Item& x,
      ::xml_schema::flags f,
      ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  title_ (x.title_, f, this),
  note_ (x.note_, f, this),
  quantity_ (x.quantity_, f, this),
  price_ (x.price_, f, this)
{
}

Item::
Item (const ::xercesc::DOMElement& e,
      ::xml_schema::flags f,
      ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  title_ (this),
  note_ (this),
  quantity_ (this),
  price_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void Item::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // title
    //
    if (n.name () == "title" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< title_type > r (
        title_traits::create (i, f, this));

      if (!title_.present ())
      {
        this->title_.set (::std::move (r));
        continue;
      }
    }

    // note
    //
    if (n.name () == "note" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< note_type > r (
        note_traits::create (i, f, this));

      if (!this->note_)
      {
        this->note_.set (::std::move (r));
        continue;
      }
    }

    // quantity
    //
    if (n.name () == "quantity" && n.namespace_ ().empty ())
    {
      if (!quantity_.present ())
      {
        this->quantity_.set (quantity_traits::create (i, f, this));
        continue;
      }
    }

    // price
    //
    if (n.name () == "price" && n.namespace_ ().empty ())
    {
      if (!price_.present ())
      {
        this->price_.set (price_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!title_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "title",
      "");
  }

  if (!quantity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "quantity",
      "");
  }

  if (!price_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "price",
      "");
  }
}

Item* Item::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class Item (*this, f, c);
}

Item& Item::
operator= (const Item& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->title_ = x.title_;
    this->note_ = x.note_;
    this->quantity_ = x.quantity_;
    this->price_ = x.price_;
  }

  return *this;
}

Item::
~Item ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::Shiporder >
Shiporder_ (const ::std::string& u,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (const ::std::string& u,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (const ::std::string& u,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Shiporder_ (isrc, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Shiporder_ (isrc, h, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Shiporder_ (isrc, h, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            const ::std::string& sid,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Shiporder_ (isrc, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            const ::std::string& sid,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Shiporder_ (isrc, h, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            const ::std::string& sid,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Shiporder_ (isrc, h, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::xercesc::InputSource& i,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::xercesc::InputSource& i,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::xercesc::InputSource& i,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (const ::xercesc::DOMDocument& doc,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::Shiporder > (
      ::Shiporder_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "Shiporder" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::Shiporder > r (
      ::xsd::cxx::tree::traits< ::Shiporder, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "Shiporder",
    "");
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
            ::xml_schema::flags f,
            const ::xml_schema::properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "Shiporder" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::Shiporder > r (
      ::xsd::cxx::tree::traits< ::Shiporder, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "Shiporder",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

void
Shiporder_ (::std::ostream& o,
            const ::Shiporder& s,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
Shiporder_ (::std::ostream& o,
            const ::Shiporder& s,
            ::xml_schema::error_handler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Shiporder_ (::std::ostream& o,
            const ::Shiporder& s,
            ::xercesc::DOMErrorHandler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Shiporder_ (::xercesc::XMLFormatTarget& t,
            const ::Shiporder& s,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
Shiporder_ (::xercesc::XMLFormatTarget& t,
            const ::Shiporder& s,
            ::xml_schema::error_handler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Shiporder_ (::xercesc::XMLFormatTarget& t,
            const ::Shiporder& s,
            ::xercesc::DOMErrorHandler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Shiporder_ (::xercesc::DOMDocument& d,
            const ::Shiporder& s,
            ::xml_schema::flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "Shiporder" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "Shiporder",
      "");
  }
}

::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
Shiporder_ (const ::Shiporder& s,
            const ::xml_schema::namespace_infomap& m,
            ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "Shiporder",
      "",
      m, f));

  ::Shiporder_ (*d, s, f);
  return d;
}

void
operator<< (::xercesc::DOMElement& e, const Shiporder& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // Orderperson
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "Orderperson",
        e));

    s << i.Orderperson ();
  }

  // Shipto
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "Shipto",
        e));

    s << i.Shipto ();
  }

  // Item
  //
  for (Shiporder::Item_const_iterator
       b (i.Item ().begin ()), n (i.Item ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "Item",
        e));

    s << *b;
  }

  // Orderid
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "Orderid",
        e));

    a << i.Orderid ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const Shipto& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // name
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "name",
        e));

    s << i.name ();
  }

  // address
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "address",
        e));

    s << i.address ();
  }

  // city
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "city",
        e));

    s << i.city ();
  }

  // country
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "country",
        e));

    s << i.country ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const Item& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // title
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "title",
        e));

    s << i.title ();
  }

  // note
  //
  if (i.note ())
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "note",
        e));

    s << *i.note ();
  }

  // quantity
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "quantity",
        e));

    s << i.quantity ();
  }

  // price
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "price",
        e));

    s << ::xml_schema::as_decimal(i.price ());
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

