// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "shiporder.h"

// Shiporder
// 

const Shiporder::orderperson_type& Shiporder::
orderperson () const
{
  return this->orderperson_.get ();
}

Shiporder::orderperson_type& Shiporder::
orderperson ()
{
  return this->orderperson_.get ();
}

void Shiporder::
orderperson (const orderperson_type& x)
{
  this->orderperson_.set (x);
}

void Shiporder::
orderperson (::std::unique_ptr< orderperson_type > x)
{
  this->orderperson_.set (std::move (x));
}

const Shiporder::shipto_type& Shiporder::
shipto () const
{
  return this->shipto_.get ();
}

Shiporder::shipto_type& Shiporder::
shipto ()
{
  return this->shipto_.get ();
}

void Shiporder::
shipto (const shipto_type& x)
{
  this->shipto_.set (x);
}

void Shiporder::
shipto (::std::unique_ptr< shipto_type > x)
{
  this->shipto_.set (std::move (x));
}

const Shiporder::item_sequence& Shiporder::
item () const
{
  return this->item_;
}

Shiporder::item_sequence& Shiporder::
item ()
{
  return this->item_;
}

void Shiporder::
item (const item_sequence& s)
{
  this->item_ = s;
}

const Shiporder::orderid_type& Shiporder::
orderid () const
{
  return this->orderid_.get ();
}

Shiporder::orderid_type& Shiporder::
orderid ()
{
  return this->orderid_.get ();
}

void Shiporder::
orderid (const orderid_type& x)
{
  this->orderid_.set (x);
}

void Shiporder::
orderid (::std::unique_ptr< orderid_type > x)
{
  this->orderid_.set (std::move (x));
}


// shipto
// 

const shipto::name_type& shipto::
name () const
{
  return this->name_.get ();
}

shipto::name_type& shipto::
name ()
{
  return this->name_.get ();
}

void shipto::
name (const name_type& x)
{
  this->name_.set (x);
}

void shipto::
name (::std::unique_ptr< name_type > x)
{
  this->name_.set (std::move (x));
}

const shipto::address_type& shipto::
address () const
{
  return this->address_.get ();
}

shipto::address_type& shipto::
address ()
{
  return this->address_.get ();
}

void shipto::
address (const address_type& x)
{
  this->address_.set (x);
}

void shipto::
address (::std::unique_ptr< address_type > x)
{
  this->address_.set (std::move (x));
}

const shipto::city_type& shipto::
city () const
{
  return this->city_.get ();
}

shipto::city_type& shipto::
city ()
{
  return this->city_.get ();
}

void shipto::
city (const city_type& x)
{
  this->city_.set (x);
}

void shipto::
city (::std::unique_ptr< city_type > x)
{
  this->city_.set (std::move (x));
}

const shipto::country_type& shipto::
country () const
{
  return this->country_.get ();
}

shipto::country_type& shipto::
country ()
{
  return this->country_.get ();
}

void shipto::
country (const country_type& x)
{
  this->country_.set (x);
}

void shipto::
country (::std::unique_ptr< country_type > x)
{
  this->country_.set (std::move (x));
}


// item
// 

const item::title_type& item::
title () const
{
  return this->title_.get ();
}

item::title_type& item::
title ()
{
  return this->title_.get ();
}

void item::
title (const title_type& x)
{
  this->title_.set (x);
}

void item::
title (::std::unique_ptr< title_type > x)
{
  this->title_.set (std::move (x));
}

const item::note_optional& item::
note () const
{
  return this->note_;
}

item::note_optional& item::
note ()
{
  return this->note_;
}

void item::
note (const note_type& x)
{
  this->note_.set (x);
}

void item::
note (const note_optional& x)
{
  this->note_ = x;
}

void item::
note (::std::unique_ptr< note_type > x)
{
  this->note_.set (std::move (x));
}

const item::quantity_type& item::
quantity () const
{
  return this->quantity_.get ();
}

item::quantity_type& item::
quantity ()
{
  return this->quantity_.get ();
}

void item::
quantity (const quantity_type& x)
{
  this->quantity_.set (x);
}

const item::price_type& item::
price () const
{
  return this->price_.get ();
}

item::price_type& item::
price ()
{
  return this->price_.get ();
}

void item::
price (const price_type& x)
{
  this->price_.set (x);
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// Shiporder
//

Shiporder::
Shiporder ()
: ::xml_schema::type (),
  orderperson_ (this),
  shipto_ (this),
  item_ (this),
  orderid_ (this)
{
}

Shiporder::
Shiporder (const orderperson_type& orderperson,
           const shipto_type& shipto,
           const orderid_type& orderid)
: ::xml_schema::type (),
  orderperson_ (orderperson, this),
  shipto_ (shipto, this),
  item_ (this),
  orderid_ (orderid, this)
{
}

Shiporder::
Shiporder (const orderperson_type& orderperson,
           ::std::unique_ptr< shipto_type > shipto,
           const orderid_type& orderid)
: ::xml_schema::type (),
  orderperson_ (orderperson, this),
  shipto_ (std::move (shipto), this),
  item_ (this),
  orderid_ (orderid, this)
{
}

Shiporder::
Shiporder (const Shiporder& x,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  orderperson_ (x.orderperson_, f, this),
  shipto_ (x.shipto_, f, this),
  item_ (x.item_, f, this),
  orderid_ (x.orderid_, f, this)
{
}

Shiporder::
Shiporder (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  orderperson_ (this),
  shipto_ (this),
  item_ (this),
  orderid_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
    this->parse (p, f);
  }
}

void Shiporder::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // orderperson
    //
    if (n.name () == "orderperson" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< orderperson_type > r (
        orderperson_traits::create (i, f, this));

      if (!orderperson_.present ())
      {
        this->orderperson_.set (::std::move (r));
        continue;
      }
    }

    // shipto
    //
    if (n.name () == "shipto" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< shipto_type > r (
        shipto_traits::create (i, f, this));

      if (!shipto_.present ())
      {
        this->shipto_.set (::std::move (r));
        continue;
      }
    }

    // item
    //
    if (n.name () == "item" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< item_type > r (
        item_traits::create (i, f, this));

      this->item_.push_back (::std::move (r));
      continue;
    }

    break;
  }

  if (!orderperson_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "orderperson",
      "");
  }

  if (!shipto_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "shipto",
      "");
  }

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "orderid" && n.namespace_ ().empty ())
    {
      this->orderid_.set (orderid_traits::create (i, f, this));
      continue;
    }
  }

  if (!orderid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "orderid",
      "");
  }
}

Shiporder* Shiporder::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class Shiporder (*this, f, c);
}

Shiporder& Shiporder::
operator= (const Shiporder& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->orderperson_ = x.orderperson_;
    this->shipto_ = x.shipto_;
    this->item_ = x.item_;
    this->orderid_ = x.orderid_;
  }

  return *this;
}

Shiporder::
~Shiporder ()
{
}

// shipto
//

shipto::
shipto ()
: ::xml_schema::type (),
  name_ (this),
  address_ (this),
  city_ (this),
  country_ (this)
{
}

shipto::
shipto (const name_type& name,
        const address_type& address,
        const city_type& city,
        const country_type& country)
: ::xml_schema::type (),
  name_ (name, this),
  address_ (address, this),
  city_ (city, this),
  country_ (country, this)
{
}

shipto::
shipto (const shipto& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  name_ (x.name_, f, this),
  address_ (x.address_, f, this),
  city_ (x.city_, f, this),
  country_ (x.country_, f, this)
{
}

shipto::
shipto (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  name_ (this),
  address_ (this),
  city_ (this),
  country_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void shipto::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // name
    //
    if (n.name () == "name" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< name_type > r (
        name_traits::create (i, f, this));

      if (!name_.present ())
      {
        this->name_.set (::std::move (r));
        continue;
      }
    }

    // address
    //
    if (n.name () == "address" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< address_type > r (
        address_traits::create (i, f, this));

      if (!address_.present ())
      {
        this->address_.set (::std::move (r));
        continue;
      }
    }

    // city
    //
    if (n.name () == "city" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< city_type > r (
        city_traits::create (i, f, this));

      if (!city_.present ())
      {
        this->city_.set (::std::move (r));
        continue;
      }
    }

    // country
    //
    if (n.name () == "country" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< country_type > r (
        country_traits::create (i, f, this));

      if (!country_.present ())
      {
        this->country_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "name",
      "");
  }

  if (!address_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "address",
      "");
  }

  if (!city_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "city",
      "");
  }

  if (!country_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "country",
      "");
  }
}

shipto* shipto::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class shipto (*this, f, c);
}

shipto& shipto::
operator= (const shipto& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->name_ = x.name_;
    this->address_ = x.address_;
    this->city_ = x.city_;
    this->country_ = x.country_;
  }

  return *this;
}

shipto::
~shipto ()
{
}

// item
//

item::
item ()
: ::xml_schema::type (),
  title_ (this),
  note_ (this),
  quantity_ (this),
  price_ (this)
{
}

item::
item (const title_type& title,
      const quantity_type& quantity,
      const price_type& price)
: ::xml_schema::type (),
  title_ (title, this),
  note_ (this),
  quantity_ (quantity, this),
  price_ (price, this)
{
}

item::
item (const item& x,
      ::xml_schema::flags f,
      ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  title_ (x.title_, f, this),
  note_ (x.note_, f, this),
  quantity_ (x.quantity_, f, this),
  price_ (x.price_, f, this)
{
}

item::
item (const ::xercesc::DOMElement& e,
      ::xml_schema::flags f,
      ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  title_ (this),
  note_ (this),
  quantity_ (this),
  price_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void item::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // title
    //
    if (n.name () == "title" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< title_type > r (
        title_traits::create (i, f, this));

      if (!title_.present ())
      {
        this->title_.set (::std::move (r));
        continue;
      }
    }

    // note
    //
    if (n.name () == "note" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< note_type > r (
        note_traits::create (i, f, this));

      if (!this->note_)
      {
        this->note_.set (::std::move (r));
        continue;
      }
    }

    // quantity
    //
    if (n.name () == "quantity" && n.namespace_ ().empty ())
    {
      if (!quantity_.present ())
      {
        this->quantity_.set (quantity_traits::create (i, f, this));
        continue;
      }
    }

    // price
    //
    if (n.name () == "price" && n.namespace_ ().empty ())
    {
      if (!price_.present ())
      {
        this->price_.set (price_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!title_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "title",
      "");
  }

  if (!quantity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "quantity",
      "");
  }

  if (!price_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "price",
      "");
  }
}

item* item::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class item (*this, f, c);
}

item& item::
operator= (const item& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->title_ = x.title_;
    this->note_ = x.note_;
    this->quantity_ = x.quantity_;
    this->price_ = x.price_;
  }

  return *this;
}

item::
~item ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::Shiporder >
Shiporder_ (const ::std::string& u,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (const ::std::string& u,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (const ::std::string& u,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Shiporder_ (isrc, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Shiporder_ (isrc, h, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Shiporder_ (isrc, h, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            const ::std::string& sid,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Shiporder_ (isrc, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            const ::std::string& sid,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Shiporder_ (isrc, h, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::std::istream& is,
            const ::std::string& sid,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Shiporder_ (isrc, h, f, p);
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::xercesc::InputSource& i,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::xercesc::InputSource& i,
            ::xml_schema::error_handler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::xercesc::InputSource& i,
            ::xercesc::DOMErrorHandler& h,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Shiporder > (
    ::Shiporder_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (const ::xercesc::DOMDocument& doc,
            ::xml_schema::flags f,
            const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::Shiporder > (
      ::Shiporder_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "Shiporder" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::Shiporder > r (
      ::xsd::cxx::tree::traits< ::Shiporder, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "Shiporder",
    "");
}

::std::unique_ptr< ::Shiporder >
Shiporder_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
            ::xml_schema::flags f,
            const ::xml_schema::properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "Shiporder" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::Shiporder > r (
      ::xsd::cxx::tree::traits< ::Shiporder, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "Shiporder",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

void
Shiporder_ (::std::ostream& o,
            const ::Shiporder& s,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
Shiporder_ (::std::ostream& o,
            const ::Shiporder& s,
            ::xml_schema::error_handler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Shiporder_ (::std::ostream& o,
            const ::Shiporder& s,
            ::xercesc::DOMErrorHandler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Shiporder_ (::xercesc::XMLFormatTarget& t,
            const ::Shiporder& s,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
Shiporder_ (::xercesc::XMLFormatTarget& t,
            const ::Shiporder& s,
            ::xml_schema::error_handler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Shiporder_ (::xercesc::XMLFormatTarget& t,
            const ::Shiporder& s,
            ::xercesc::DOMErrorHandler& h,
            const ::xml_schema::namespace_infomap& m,
            const ::std::string& e,
            ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Shiporder_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Shiporder_ (::xercesc::DOMDocument& d,
            const ::Shiporder& s,
            ::xml_schema::flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "Shiporder" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "Shiporder",
      "");
  }
}

::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
Shiporder_ (const ::Shiporder& s,
            const ::xml_schema::namespace_infomap& m,
            ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "Shiporder",
      "",
      m, f));

  ::Shiporder_ (*d, s, f);
  return d;
}

void
operator<< (::xercesc::DOMElement& e, const Shiporder& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // orderperson
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "orderperson",
        e));

    s << i.orderperson ();
  }

  // shipto
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "shipto",
        e));

    s << i.shipto ();
  }

  // item
  //
  for (Shiporder::item_const_iterator
       b (i.item ().begin ()), n (i.item ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "item",
        e));

    s << *b;
  }

  // orderid
  //
  {
    ::xercesc::DOMAttr& a (
      ::xsd::cxx::xml::dom::create_attribute (
        "orderid",
        e));

    a << i.orderid ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const shipto& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // name
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "name",
        e));

    s << i.name ();
  }

  // address
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "address",
        e));

    s << i.address ();
  }

  // city
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "city",
        e));

    s << i.city ();
  }

  // country
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "country",
        e));

    s << i.country ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const item& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // title
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "title",
        e));

    s << i.title ();
  }

  // note
  //
  if (i.note ())
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "note",
        e));

    s << *i.note ();
  }

  // quantity
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "quantity",
        e));

    s << i.quantity ();
  }

  // price
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "price",
        e));

    s << ::xml_schema::as_decimal(i.price ());
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

